<?php

$site_config = [
    'site_name' => 'xpsystems Domains',
    'version' => 'v2.2.1',
    'current_year' => date('Y'),
];

$active_domains = [
    [
        'category' => 'Personal & Identity',
        'icon' => 'user',
        'links' => [
            ['url' => 'https://fternis.de', 'label' => 'fternis.de'],
            ['url' => 'https://fabianternis.dev', 'label' => 'fabianternis.dev'],
            ['url' => 'https://fabianternis.de', 'label' => 'fabianternis.de'],
            ['url' => 'https://fabian-ternis.de', 'label' => 'fabian-ternis.de'],
            ['url' => 'https://ternis.eu', 'label' => 'ternis.eu'],
            ['url' => 'https://ivoternis.de', 'label' => 'ivoternis.de'],
            ['url' => 'https://mysocials.me', 'label' => 'mysocials.me'],
            ['url' => 'https://getsocials.link', 'label' => 'getsocials.link'],
            ['url' => 'https://linkmy.name', 'label' => 'linkmy.name'],
            ['url' => 'https://pleasehireme.eu', 'label' => 'pleasehireme.eu'],
            ['url' => 'https://pleasehireme.de', 'label' => 'pleasehireme.de'],
        ]
    ],
    [
        'category' => 'XP-Systems Network',
        'icon' => 'server',
        'highlight' => true,
        'links' => [
            ['url' => 'https://xpsystems.eu', 'label' => 'xpsystems.eu'],
            ['url' => 'https://xpsystems.de', 'label' => 'xpsystems.de'],
            ['url' => 'https://xpsys.de', 'label' => 'xpsys.de'],
            ['url' => 'https://xp-ad.de', 'label' => 'xp-ad.de'],
            ['url' => 'https://ptero01.eu', 'label' => 'ptero01.eu'],
            ['url' => 'https://epyc01.eu', 'label' => 'epyc01.eu'],
            ['url' => 'https://ryzen01.eu', 'label' => 'ryzen01.eu'],
        ]
    ],
    [
        'category' => 'Europehost.eu Network',
        'icon' => 'globe',
        'links' => [
            ['url' => 'https://europehost.eu', 'label' => 'europehost.eu'],
            ['url' => 'https://eudomains.eu', 'label' => 'eudomains.eu'],
            ['url' => 'https://eushare.eu', 'label' => 'eushare.eu'],
            ['url' => 'https://domaingen.de', 'label' => 'domaingen.de'],
            ['url' => 'https://dsc.pics', 'label' => 'dsc.pics', 'badge' => 'GitHub'],
            ['url' => 'https://dcpic.eu', 'label' => 'dcpic.eu', 'badge' => 'GitHub'],
            ['url' => 'https://twch.pics', 'label' => 'twch.pics'],
            ['url' => 'https://mcserver.lol', 'label' => 'mcserver.lol'],
        ]
    ],
    [
        'category' => 'Mtex.dev & Projects',
        'icon' => 'code',
        'links' => [
            ['url' => 'https://mtex.dev', 'label' => 'mtex.dev', 'badge' => 'GitHub'],
            ['url' => 'https://api-sandbox.de', 'label' => 'api-sandbox.de', 'badge' => 'GitHub'],
            ['url' => 'https://sandbox-api.de', 'label' => 'sandbox-api.de'],
            ['url' => 'https://gimy.site', 'label' => 'gimy.site', 'badge' => 'GitHub'],
            ['url' => 'https://getmy.blog', 'label' => 'getmy.blog'],
            ['url' => 'https://getmy.name', 'label' => 'getmy.name'],
            ['url' => 'https://urlk.app', 'label' => 'urlk.app'],
            ['url' => 'https://yourlink.app', 'label' => 'yourlink.app'],
            ['url' => 'https://csslib.eu', 'label' => 'csslib.eu'],
        ]
    ],
    [
        'category' => 'Official & Protection',
        'icon' => 'shield',
        'links' => [
            ['url' => 'https://bank-of-germany.de', 'label' => 'bank-of-germany.de'],
            ['url' => 'https://hhg-kl.eu', 'label' => 'hhg-kl.eu'],
            ['url' => 'https://staatliches-heinrich-heine-gymnasium-kaiserslautern.de',
              'label' => 'staatliches-heinrich-heine-gymnasium...'],
            ['url' => 'https://bildungsbereich-rlp.de', 'label' => 'bildungsbereich-rlp.de'],
        ]
    ],
    [
        'category' => 'Other Active Domains',
        'icon' => 'folder',
        'links' => [
            ['url' => 'https://kaufenhof.de', 'label' => 'kaufenhof.de', 'badge' => 'Client'],
            ['url' => 'https://heimatverein-floersheim-dalsheim.de', 
              'label' => 'heimatverein-floersheim-dalsheim.de'],
            ['url' => 'https://woistdasdrachenei.de', 'label' => 'woistdasdrachenei.de'],
            ['url' => 'https://2note.eu', 'label' => '2note.eu'],
            ['url' => 'https://burgermc.de', 'label' => 'burgermc.de'],
            ['url' => 'https://laravel-tutorial.eu', 'label' => 'laravel-tutorial.eu'],
            ['url' => 'https://gehirn-weg.de', 'label' => 'gehirn-weg.de'],
            ['url' => 'https://spielefrei.de', 'label' => 'spielefrei.de'],
            ['url' => 'https://xpgames.eu', 'label' => 'xpgames.eu'],
            ['url' => 'https://192-168-0-1.de', 'label' => '192-168-0-1.de'],
            ['url' => 'https://mail-free.eu', 'label' => 'mail-free.eu', 'badge' => 'GitHub'],
            ['url' => 'https://eu-data.org', 'label' => 'eu-data.org', 'badge' => 'GitHub'],
            ['url' => 'https://eu-search.org', 'label' => 'eu-search.org', 'badge' => 'GitHub'],
            ['url' => 'https://web-search.org', 'label' => 'web-search.org', 'badge' => 'GitHub'],
        ]
    ],
];

$legacy_domains = [
    'category' => 'Legacy (Expired)',
    'icon' => 'archive',
    'links' => [
        ['label' => 'xp-craft.de'],
        ['label' => 'darkangel-mc.de'],
        ['label' => 'xp-host.de'],
        ['label' => 'ebay-konto.de'],
        ['label' => 'citycraft-nw.de'],
        ['label' => 'mail-free.de'],
        ['label' => 'michaelninder.de'],
        ['label' => 'xp-link.de'],
        ['label' => 'xp-node.de'],
        ['label' => 'dexify.eu'],
        ['label' => 'xp-cloud.eu'],
        ['label' => 'code-trainer.de'],
        ['label' => 'a-sub.de'],
        ['label' => 'b-sub.de'],
        ['label' => 'hhgkl.de'],
        ['label' => 'citycraft-smp.de'],
        ['label' => 'quizhive.de'],
        ['label' => 'bank-of-europe.eu'],
        ['label' => 'craftattack.xyz'],
        ['label' => 'euromc.eu'],
        ['label' => 'xp-h.de'],
        ['label' => 'xp-l.de'],
        ['label' => 'sub2.eu'],
        ['label' => 'webstruct.eu'],
        ['label' => 'mcservertools.eu'],
        ['label' => 'xphost.eu'],
        ['label' => 'mcpractice.eu'],
        ['label' => 'novastack.eu'],
        ['label' => 'flexistack.eu'],
        ['label' => 'pelicanhost.eu'],
        ['label' => 'axiohost.eu'],
        ['label' => 'axiohost.de'],
        ['label' => 'city-craft.de'],
        ['label' => 'xp-domains.de'],
        ['label' => 'xp-domain.de'],
        ['label' => 'xfolio.eu'],
        ['label' => 'eupractice.eu'],
        ['label' => 'soulnode.eu'],
        ['label' => 'schulchat-rlp.de'],
        ['label' => 'nerax.eu'],
        ['label' => 'anlink.eu'],
        ['label' => 'mchost24.eu'],
        ['label' => '24mc.eu'],
        ['label' => 'schulkampus-rlp.de'],
        ['label' => 'bildungslogin-rlp.de'],
        ['label' => 'xp-mail.eu'],
        ['label' => 'pythonhub.eu'],
        ['label' => 'xmage.eu'],
        ['label' => 'imagu.eu'],
        ['label' => 'swiftshare.eu'],
        ['label' => 'pyshop.de'],
    ]
];
?>
